//
//  TimeZoneFlags.swift
//  TimeZoneFlags
//
//  Created by Ben Cardy on 11/09/2021.
//

import Foundation

let NoFlagTimeZoneEmoji = "⏰"

func flagForTimeZone(_ zone: TimeZone) -> String {
    return flagForTimeZone(zone.identifier)
}

func flagForTimeZone(_ zone: String) -> String {
    return timeZoneFlags[zone] ?? NoFlagTimeZoneEmoji
}

let timeZoneFlags: [String: String] = [
    "Africa/Abidjan": "🇨🇮",
    "Africa/Accra": "🇬🇭",
    "Africa/Addis_Ababa": "🇪🇹",
    "Africa/Algiers": "🇩🇿",
    "Africa/Asmara": "🇪🇷",
    "Africa/Bamako": "🇲🇱",
    "Africa/Bangui": "🇨🇫",
    "Africa/Banjul": "🇬🇲",
    "Africa/Bissau": "🇬🇳",
    "Africa/Blantyre": "🇲🇼",
    "Africa/Brazzaville": "🇨🇬",
    "Africa/Bujumbura": "🇧🇮",
    "Africa/Cairo": "🇪🇬",
    "Africa/Casablanca": "🇲🇦",
    "Africa/Ceuta": "🇪🇸",
    "Africa/Conakry": "🇬🇳",
    "Africa/Dakar": "🇸🇳",
    "Africa/Dar_es_Salaam": "🇹🇿",
    "Africa/Djibouti": "🇩🇯",
    "Africa/Douala": "🇨🇲",
    "Africa/El_Aaiun": "🇪🇭",
    "Africa/Freetown": "🇸🇱",
    "Africa/Gaborone": "🇧🇼",
    "Africa/Harare": "🇿🇼",
    "Africa/Johannesburg": "🇿🇦",
    "Africa/Juba": "🇸🇸",
    "Africa/Kampala": "🇺🇬",
    "Africa/Khartoum": "🇸🇩",
    "Africa/Kigali": "🇷🇼",
    "Africa/Kinshasa": "🇨🇩",
    "Africa/Lagos": "🇳🇬",
    "Africa/Libreville": "🇬🇦",
    "Africa/Lome": "🇹🇬",
    "Africa/Luanda": "🇦🇴",
    "Africa/Lubumbashi": "🇨🇩",
    "Africa/Lusaka": "🇿🇲",
    "Africa/Malabo": "🇬🇶",
    "Africa/Maputo": "🇲🇿",
    "Africa/Maseru": "🇱🇸",
    "Africa/Mbabane": "🇸🇿",
    "Africa/Mogadishu": "🇸🇴",
    "Africa/Monrovia": "🇱🇷",
    "Africa/Nairobi": "🇰🇪",
    "Africa/Ndjamena": "🇹🇩",
    "Africa/Niamey": "🇳🇪",
    "Africa/Nouakchott": "🇲🇷",
    "Africa/Ouagadougou": "🇧🇫",
    "Africa/Porto-Novo": "🇧🇯",
    "Africa/Sao_Tome": "🇸🇹",
    "Africa/Tripoli": "🇱🇾",
    "Africa/Tunis": "🇹🇳",
    "Africa/Windhoek": "🇳🇦",
    "America/Adak": "🇺🇸",
    "America/Anchorage": "🇺🇸",
    "America/Anguilla": "🇦🇮",
    "America/Antigua": "🇦🇬",
    "America/Araguaina": "🇧🇷",
    "America/Argentina/Buenos_Aires": "🇦🇷",
    "America/Argentina/Catamarca": "🇦🇷",
    "America/Argentina/Cordoba": "🇦🇷",
    "America/Argentina/Jujuy": "🇦🇷",
    "America/Argentina/La_Rioja": "🇦🇷",
    "America/Argentina/Mendoza": "🇦🇷",
    "America/Argentina/Rio_Gallegos": "🇦🇷",
    "America/Argentina/Salta": "🇦🇷",
    "America/Argentina/San_Juan": "🇦🇷",
    "America/Argentina/San_Luis": "🇦🇷",
    "America/Argentina/Tucuman": "🇦🇷",
    "America/Argentina/Ushuaia": "🇦🇷",
    "America/Aruba": "🇦🇼",
    "America/Asuncion": "🇵🇾",
    "America/Atikokan": "🇨🇦",
    "America/Bahia": "🇧🇷",
    "America/Bahia_Banderas": "🇲🇽",
    "America/Barbados": "🇧🇧",
    "America/Belem": "🇧🇷",
    "America/Belize": "🇧🇿",
    "America/Blanc-Sablon": "🇨🇦",
    "America/Boa_Vista": "🇨🇻",
    "America/Bogota": "🇨🇴",
    "America/Boise": "🇺🇸",
    "America/Cambridge_Bay": "🇨🇦",
    "America/Campo_Grande": "🇧🇷",
    "America/Cancun": "🇲🇽",
    "America/Caracas": "🇻🇪",
    "America/Cayenne": "🇬🇫",
    "America/Cayman": "🇰🇾",
    "America/Chicago": "🇺🇸",
    "America/Chihuahua": "🇲🇽",
    "America/Costa_Rica": "🇨🇷",
    "America/Creston": "🇨🇦",
    "America/Cuiaba": "🇧🇷",
    "America/Curacao": "🇨🇼",
    "America/Danmarkshavn": "🇬🇱",
    "America/Dawson": "🇨🇦",
    "America/Dawson_Creek": "🇨🇦",
    "America/Denver": "🇺🇸",
    "America/Detroit": "🇺🇸",
    "America/Dominica": "🇩🇲",
    "America/Edmonton": "🇨🇦",
    "America/Eirunepe": "🇧🇷",
    "America/El_Salvador": "🇸🇻",
    "America/Fort_Nelson": "🇨🇦",
    "America/Fortaleza": "🇧🇷",
    "America/Glace_Bay": "🇨🇦",
    "America/Godthab": "🇬🇱",
    "America/Goose_Bay": "🇨🇦",
    "America/Grand_Turk": "🇹🇨",
    "America/Grenada": "🇬🇩",
    "America/Guadeloupe": "🇬🇵",
    "America/Guatemala": "🇬🇹",
    "America/Guayaquil": "🇪🇨",
    "America/Guyana": "🇬🇾",
    "America/Halifax": "🇨🇦",
    "America/Havana": "🇨🇺",
    "America/Hermosillo": "🇲🇽",
    "America/Indiana/Indianapolis": "🇺🇸",
    "America/Indiana/Knox": "🇺🇸",
    "America/Indiana/Marengo": "🇺🇸",
    "America/Indiana/Petersburg": "🇺🇸",
    "America/Indiana/Tell_City": "🇺🇸",
    "America/Indiana/Vevay": "🇺🇸",
    "America/Indiana/Vincennes": "🇺🇸",
    "America/Indiana/Winamac": "🇺🇸",
    "America/Inuvik": "🇨🇦",
    "America/Iqaluit": "🇨🇦",
    "America/Jamaica": "🇯🇲",
    "America/Juneau": "🇺🇸",
    "America/Kentucky/Louisville": "🇺🇸",
    "America/Kentucky/Monticello": "🇺🇸",
    "America/Kralendijk": "🇧🇶",
    "America/La_Paz": "🇧🇴",
    "America/Lima": "🇵🇪",
    "America/Los_Angeles": "🇺🇸",
    "America/Lower_Princes": "🇸🇽",
    "America/Maceio": "🇧🇷",
    "America/Managua": "🇳🇮",
    "America/Manaus": "🇧🇷",
    "America/Marigot": "🇲🇫",
    "America/Martinique": "🇲🇶",
    "America/Matamoros": "🇲🇽",
    "America/Mazatlan": "🇲🇽",
    "America/Menominee": "🇺🇸",
    "America/Merida": "🇲🇽",
    "America/Metlakatla": "🇺🇸",
    "America/Mexico_City": "🇲🇽",
    "America/Miquelon": "🇵🇲",
    "America/Moncton": "🇨🇦",
    "America/Monterrey": "🇲🇽",
    "America/Montevideo": "🇺🇾",
    "America/Montreal": "🇨🇦",
    "America/Montserrat": "🇲🇸",
    "America/Nassau": "🇧🇸",
    "America/New_York": "🇺🇸",
    "America/Nipigon": "🇨🇦",
    "America/Nome": "🇺🇸",
    "America/Noronha": "🇧🇷",
    "America/North_Dakota/Beulah": "🇺🇸",
    "America/North_Dakota/Center": "🇺🇸",
    "America/North_Dakota/New_Salem": "🇺🇸",
    "America/Nuuk": "🇬🇱",
    "America/Ojinaga": "🇲🇽",
    "America/Panama": "🇵🇦",
    "America/Pangnirtung": "🇨🇦",
    "America/Paramaribo": "🇸🇷",
    "America/Phoenix": "🇺🇸",
    "America/Port-au-Prince": "🇭🇹",
    "America/Port_of_Spain": "🇹🇹",
    "America/Porto_Velho": "🇧🇷",
    "America/Puerto_Rico": "🇵🇷",
    "America/Punta_Arenas": "🇨🇱",
    "America/Rainy_River": "🇨🇦",
    "America/Rankin_Inlet": "🇨🇦",
    "America/Recife": "🇧🇷",
    "America/Regina": "🇨🇦",
    "America/Resolute": "🇨🇦",
    "America/Rio_Branco": "🇧🇷",
    "America/Santa_Isabel": "",
    "America/Santarem": "🇧🇷",
    "America/Santiago": "🇨🇱",
    "America/Santo_Domingo": "🇩🇴",
    "America/Sao_Paulo": "🇧🇷",
    "America/Scoresbysund": "🇬🇱",
    "America/Shiprock": "🇺🇸",
    "America/Sitka": "🇺🇸",
    "America/St_Barthelemy": "🇧🇱",
    "America/St_Johns": "🇨🇦",
    "America/St_Kitts": "🇰🇳",
    "America/St_Lucia": "🇱🇨",
    "America/St_Thomas": "🇻🇮",
    "America/St_Vincent": "🇻🇨",
    "America/Swift_Current": "🇨🇦",
    "America/Tegucigalpa": "🇭🇳",
    "America/Thule": "🇬🇱",
    "America/Thunder_Bay": "🇨🇦",
    "America/Tijuana": "🇲🇽",
    "America/Toronto": "🇨🇦",
    "America/Tortola": "🇻🇬",
    "America/Vancouver": "🇨🇦",
    "America/Whitehorse": "🇨🇦",
    "America/Winnipeg": "🇨🇦",
    "America/Yakutat": "🇺🇸",
    "America/Yellowknife": "🇨🇦",
    "Antarctica/Casey": "🇦🇶",
    "Antarctica/Davis": "🇦🇶",
    "Antarctica/DumontDUrville": "🇦🇶",
    "Antarctica/Macquarie": "🇦🇶",
    "Antarctica/Mawson": "🇦🇶",
    "Antarctica/McMurdo": "🇦🇶",
    "Antarctica/Palmer": "🇦🇶",
    "Antarctica/Rothera": "🇦🇶",
    "Antarctica/South_Pole": "🇦🇶",
    "Antarctica/Syowa": "🇦🇶",
    "Antarctica/Troll": "🇦🇶",
    "Antarctica/Vostok": "🇦🇶",
    "Arctic/Longyearbyen": "🇸🇯",
    "Asia/Aden": "🇾🇪",
    "Asia/Almaty": "🇰🇿",
    "Asia/Amman": "🇯🇴",
    "Asia/Anadyr": "🇷🇺",
    "Asia/Aqtau": "🇰🇿",
    "Asia/Aqtobe": "🇰🇿",
    "Asia/Ashgabat": "🇹🇲",
    "Asia/Atyrau": "🇰🇿",
    "Asia/Baghdad": "🇮🇶",
    "Asia/Bahrain": "🇧🇭",
    "Asia/Baku": "🇦🇿",
    "Asia/Bangkok": "🇹🇭",
    "Asia/Barnaul": "🇷🇺",
    "Asia/Beirut": "🇱🇧",
    "Asia/Bishkek": "🇰🇬",
    "Asia/Brunei": "🇧🇳",
    "Asia/Calcutta": "🇮🇳",
    "Asia/Chita": "🇷🇺",
    "Asia/Choibalsan": "🇲🇳",
    "Asia/Chongqing": "🇨🇳",
    "Asia/Colombo": "🇱🇰",
    "Asia/Damascus": "🇸🇾",
    "Asia/Dhaka": "🇧🇩",
    "Asia/Dili": "🇹🇱",
    "Asia/Dubai": "🇦🇪",
    "Asia/Dushanbe": "🇹🇯",
    "Asia/Famagusta": "🇨🇾",
    "Asia/Gaza": "🇵🇸",
    "Asia/Harbin": "🇨🇳",
    "Asia/Hebron": "🇵🇸",
    "Asia/Ho_Chi_Minh": "🇻🇳",
    "Asia/Hong_Kong": "🇭🇰",
    "Asia/Hovd": "🇲🇳",
    "Asia/Irkutsk": "🇷🇺",
    "Asia/Jakarta": "🇮🇩",
    "Asia/Jayapura": "🇮🇩",
    "Asia/Kabul": "🇦🇫",
    "Asia/Kamchatka": "🇷🇺",
    "Asia/Karachi": "🇵🇰",
    "Asia/Kashgar": "🇨🇳",
    "Asia/Kathmandu": "🇳🇵",
    "Asia/Katmandu": "🇳🇵",
    "Asia/Khandyga": "🇷🇺",
    "Asia/Krasnoyarsk": "🇷🇺",
    "Asia/Kuala_Lumpur": "🇲🇾",
    "Asia/Kuching": "🇲🇾",
    "Asia/Kuwait": "🇰🇼",
    "Asia/Macau": "🇲🇴",
    "Asia/Magadan": "🇷🇺",
    "Asia/Makassar": "🇮🇩",
    "Asia/Manila": "🇵🇭",
    "Asia/Muscat": "🇴🇲",
    "Asia/Nicosia": "🇨🇾",
    "Asia/Novokuznetsk": "🇷🇺",
    "Asia/Novosibirsk": "🇷🇺",
    "Asia/Omsk": "🇷🇺",
    "Asia/Oral": "🇰🇿",
    "Asia/Phnom_Penh": "🇰🇭",
    "Asia/Pontianak": "🇮🇩",
    "Asia/Pyongyang": "🇰🇵",
    "Asia/Qatar": "🇶🇦",
    "Asia/Qostanay": "🇰🇿",
    "Asia/Qyzylorda": "🇰🇿",
    "Asia/Rangoon": "🇲🇲",
    "Asia/Riyadh": "🇸🇦",
    "Asia/Sakhalin": "🇷🇺",
    "Asia/Samarkand": "🇺🇿",
    "Asia/Seoul": "🇰🇷",
    "Asia/Shanghai": "🇨🇳",
    "Asia/Singapore": "🇸🇬",
    "Asia/Srednekolymsk": "🇷🇺",
    "Asia/Taipei": "🇹🇼",
    "Asia/Tashkent": "🇺🇿",
    "Asia/Tbilisi": "🇬🇪",
    "Asia/Tehran": "🇮🇷",
    "Asia/Thimphu": "🇧🇹",
    "Asia/Tokyo": "🇯🇵",
    "Asia/Tomsk": "🇷🇺",
    "Asia/Ulaanbaatar": "🇲🇳",
    "Asia/Urumqi": "🇨🇳",
    "Asia/Ust-Nera": "🇷🇺",
    "Asia/Vientiane": "🇱🇦",
    "Asia/Vladivostok": "🇷🇺",
    "Asia/Yakutsk": "🇷🇺",
    "Asia/Yangon": "🇲🇲",
    "Asia/Yekaterinburg": "🇷🇺",
    "Asia/Yerevan": "🇦🇲",
    "Atlantic/Azores": "🇵🇹",
    "Atlantic/Bermuda": "🇧🇲",
    "Atlantic/Canary": "🇪🇸",
    "Atlantic/Cape_Verde": "🇨🇻",
    "Atlantic/Faroe": "🇫🇴",
    "Atlantic/Madeira": "🇵🇹",
    "Atlantic/Reykjavik": "🇮🇸",
    "Atlantic/South_Georgia": "🇬🇸",
    "Atlantic/St_Helena": "🇸🇭",
    "Atlantic/Stanley": "🇫🇰",
    "Australia/Adelaide": "🇦🇺",
    "Australia/Brisbane": "🇦🇺",
    "Australia/Broken_Hill": "🇦🇺",
    "Australia/Currie": "🇦🇺",
    "Australia/Darwin": "🇦🇺",
    "Australia/Eucla": "🇦🇺",
    "Australia/Hobart": "🇦🇺",
    "Australia/Lindeman": "🇦🇺",
    "Australia/Lord_Howe": "🇦🇺",
    "Australia/Melbourne": "🇦🇺",
    "Australia/Perth": "🇦🇺",
    "Australia/Sydney": "🇦🇺",
    "Europe/Amsterdam": "🇳🇱",
    "Europe/Andorra": "🇦🇩",
    "Europe/Astrakhan": "🇷🇺",
    "Europe/Athens": "🇬🇷",
    "Europe/Belgrade": "🇷🇸",
    "Europe/Berlin": "🇩🇪",
    "Europe/Bratislava": "🇸🇰",
    "Europe/Brussels": "🇧🇪",
    "Europe/Bucharest": "🇷🇴",
    "Europe/Budapest": "🇭🇺",
    "Europe/Busingen": "🇩🇪",
    "Europe/Chisinau": "🇲🇩",
    "Europe/Copenhagen": "🇩🇰",
    "Europe/Dublin": "🇮🇪",
    "Europe/Gibraltar": "🇬🇮",
    "Europe/Guernsey": "🇬🇬",
    "Europe/Helsinki": "🇫🇮",
    "Europe/Isle_of_Man": "🇬🇧",
    "Europe/Istanbul": "🇹🇷",
    "Europe/Jersey": "🇯🇪",
    "Europe/Kaliningrad": "🇷🇺",
    "Europe/Kiev": "🇺🇦",
    "Europe/Kirov": "🇷🇺",
    "Europe/Lisbon": "🇵🇹",
    "Europe/Ljubljana": "🇸🇮",
    "Europe/London": "🇬🇧",
    "Europe/Luxembourg": "🇱🇺",
    "Europe/Madrid": "🇪🇸",
    "Europe/Malta": "🇲🇹",
    "Europe/Mariehamn": "🇫🇮",
    "Europe/Minsk": "🇧🇾",
    "Europe/Monaco": "🇲🇨",
    "Europe/Moscow": "🇷🇺",
    "Europe/Oslo": "🇳🇴",
    "Europe/Paris": "🇫🇷",
    "Europe/Podgorica": "🇲🇪",
    "Europe/Prague": "🇨🇿",
    "Europe/Riga": "🇱🇻",
    "Europe/Rome": "🇮🇹",
    "Europe/Samara": "🇷🇺",
    "Europe/San_Marino": "🇸🇲",
    "Europe/Sarajevo": "🇧🇦",
    "Europe/Saratov": "🇷🇺",
    "Europe/Simferopol": "🇷🇺",
    "Europe/Skopje": "🇲🇰",
    "Europe/Sofia": "🇧🇬",
    "Europe/Stockholm": "🇸🇪",
    "Europe/Tallinn": "🇪🇪",
    "Europe/Tirane": "🇦🇱",
    "Europe/Ulyanovsk": "🇷🇺",
    "Europe/Uzhgorod": "🇺🇦",
    "Europe/Vaduz": "🇱🇮",
    "Europe/Vatican": "🇻🇦",
    "Europe/Vienna": "🇦🇹",
    "Europe/Vilnius": "🇱🇹",
    "Europe/Volgograd": "🇷🇺",
    "Europe/Warsaw": "🇵🇱",
    "Europe/Zagreb": "🇭🇷",
    "Europe/Zaporozhye": "🇺🇦",
    "Europe/Zurich": "🇨🇭",
    "Indian/Antananarivo": "🇲🇬",
    "Indian/Chagos": "🇮🇴",
    "Indian/Christmas": "🇨🇽",
    "Indian/Cocos": "🇨🇨",
    "Indian/Comoro": "🇰🇲",
    "Indian/Kerguelen": "🇹🇫",
    "Indian/Mahe": "🇸🇨",
    "Indian/Maldives": "🇲🇻",
    "Indian/Mauritius": "🇲🇺",
    "Indian/Mayotte": "🇾🇹",
    "Indian/Reunion": "🇷🇪",
    "Pacific/Apia": "🇼🇸",
    "Pacific/Auckland": "🇳🇿",
    "Pacific/Bougainville": "🇵🇬",
    "Pacific/Chatham": "🇳🇿",
    "Pacific/Chuuk": "🇫🇲",
    "Pacific/Easter": "🇨🇱",
    "Pacific/Efate": "🇻🇺",
    "Pacific/Enderbury": "🇰🇮",
    "Pacific/Fakaofo": "🇹🇰",
    "Pacific/Fiji": "🇫🇯",
    "Pacific/Funafuti": "🇹🇻",
    "Pacific/Galapagos": "🇪🇨",
    "Pacific/Gambier": "🇵🇫",
    "Pacific/Guadalcanal": "🇸🇧",
    "Pacific/Guam": "🇬🇺",
    "Pacific/Honolulu": "🇺🇸",
    "Pacific/Johnston": "🇺🇸",
    "Pacific/Kiritimati": "🇰🇮",
    "Pacific/Kosrae": "🇫🇲",
    "Pacific/Kwajalein": "🇲🇭",
    "Pacific/Majuro": "🇲🇭",
    "Pacific/Marquesas": "🇵🇫",
    "Pacific/Midway": "🇺🇸",
    "Pacific/Nauru": "🇳🇷",
    "Pacific/Niue": "🇳🇺",
    "Pacific/Norfolk": "🇳🇫",
    "Pacific/Noumea": "🇳🇨",
    "Pacific/Pago_Pago": "🇦🇸",
    "Pacific/Palau": "🇵🇼",
    "Pacific/Pitcairn": "🇵🇳",
    "Pacific/Pohnpei": "🇫🇲",
    "Pacific/Ponape": "🇫🇲",
    "Pacific/Port_Moresby": "🇵🇬",
    "Pacific/Rarotonga": "🇨🇰",
    "Pacific/Saipan": "🇲🇵",
    "Pacific/Tahiti": "🇵🇫",
    "Pacific/Tarawa": "🇰🇮",
    "Pacific/Tongatapu": "🇹🇴",
    "Pacific/Truk": "🇫🇲",
    "Pacific/Wake": "🇺🇸",
    "Pacific/Wallis": "🇼🇫",
    "IST": "🇮🇳",
]

let europeanUnionTimeZones: Set<String> = [
    "Europe/Amsterdam",
    "Europe/Athens",
    "Europe/Berlin",
    "Europe/Bratislava",
    "Europe/Brussels",
    "Europe/Bucharest",
    "Europe/Budapest",
    "Europe/Busingen",
    "Europe/Copenhagen",
    "Europe/Dublin",
    "Europe/Helsinki",
    "Europe/Lisbon",
    "Europe/Ljubljana",
    "Europe/Luxembourg",
    "Europe/Madrid",
    "Europe/Malta",
    "Europe/Mariehamn",
    "Europe/Paris",
    "Europe/Prague",
    "Europe/Riga",
    "Europe/Rome",
    "Europe/Sofia",
    "Europe/Stockholm",
    "Europe/Tallinn",
    "Europe/Vienna",
    "Europe/Vilnius",
    "Europe/Warsaw",
    "Europe/Zagreb",
]

let timeZoneCountries: [String: String] = [
    "Africa/Abidjan" : "Ivory Coast, Côte d'Ivoire",
    "Africa/Accra" : "Ghana",
    "Africa/Addis_Ababa" : "Ethiopia",
    "Africa/Algiers" : "Algeria",
    "Africa/Asmara" : "Eritrea",
    "Africa/Bamako" : "Mali",
    "Africa/Bangui" : "Central African Republic",
    "Africa/Banjul" : "Gambia",
    "Africa/Bissau" : "Guinea-Bissau",
    "Africa/Blantyre" : "Malawi",
    "Africa/Brazzaville" : "Congo",
    "Africa/Bujumbura" : "Burundi",
    "Africa/Cairo" : "Egypt",
    "Africa/Casablanca" : "Morocco",
    "Africa/Conakry" : "Guinea",
    "Africa/Dakar" : "Senegal",
    "Africa/Dar_es_Salaam" : "Tanzania",
    "Africa/Djibouti" : "East Africa",
    "Africa/Douala" : "Cameroon",
    "Africa/Freetown" : "Sierra Leone",
    "Africa/Gaborone" : "Botswana",
    "Africa/Harare" : "Zimbabwe",
    "Africa/Johannesburg" : "South Africa",
    "Africa/Juba" : "South Sudan",
    "Africa/Kampala" : "Uganda",
    "Africa/Khartoum" : "Sudan",
    "Africa/Kigali" : "Rwanda",
    "Africa/Kinshasa" : "Democractic Republic of the Congo",
    "Africa/Lagos" : "Nigeria",
    "Africa/Libreville" : "Gabon",
    "Africa/Lome" : "Togo",
    "Africa/Luanda" : "Angola",
    "Africa/Lubumbashi" : "Democractic Republic of the Congo",
    "Africa/Lusaka" : "Zambia",
    "Africa/Malabo" : "Equatorial Guinea",
    "Africa/Maputo" : "Mozambique",
    "Africa/Maseru" : "Lesotho",
    "Africa/Mbabane" : "Swaziland",
    "Africa/Mogadishu" : "Somalia",
    "Africa/Monrovia" : "Liberia",
    "Africa/Nairobi" : "Kenya",
    "Africa/Ndjamena" : "Chad",
    "Africa/Niamey" : "Niger",
    "Africa/Nouakchott" : "Mauritania",
    "Africa/Ouagadougou" : "Brukina Faso",
    "Africa/Porto-Novo" : "Benin",
    "Africa/Sao_Tome" : "Central Africa",
    "Africa/Tripoli" : "Libya",
    "Africa/Tunis" : "Tunisia",
    "Africa/Windhoek" : "Namibia",
    "America/Adak" : "United States",
    "America/Anchorage" : "United States",
    "America/Araguaina" : "Brazil",
    "America/Asuncion" : "Paraguay",
    "America/Atikokan" : "Canada",
    "America/Bahia" : "Brazil",
    "America/Bahia_Banderas" : "Mexico",
    "America/Belem" : "Brazil",
    "America/Belize" : "Belize",
    "America/Blanc-Sablon" : "Canada",
    "America/Boa_Vista" : "Brazil",
    "America/Bogota" : "Colombia",
    "America/Boise" : "United States",
    "America/Cambridge_Bay" : "Canada",
    "America/Campo_Grande" : "Brazil",
    "America/Cancun" : "Mexico",
    "America/Caracas" : "Venezuela",
    "America/Cayenne" : "French Guiana",
    "America/Cayman" : "Cayman Islands",
    "America/Chicago" : "United States",
    "America/Chihuahua" : "Mexico",
    "America/Costa_Rica" : "Costa Rica",
    "America/Creston" : "Canada",
    "America/Cuiaba" : "Brazil",
    "America/Curacao" : "Curacao",
    "America/Danmarkshavn" : "Greenland",
    "America/Dawson" : "Canada",
    "America/Dawson_Creek" : "Canada",
    "America/Denver" : "United States",
    "America/Detroit" : "United States",
    "America/Dominica" : "Dominica",
    "America/Edmonton" : "Canada",
    "America/Eirunepe" : "Brazil",
    "America/El_Salvador" : "El Salvador",
    "America/Fort_Nelson" : "Canada",
    "America/Fortaleza" : "Brazil",
    "America/Glace_Bay" : "Canada",
    "America/Godthab" : "Greenland",
    "America/Goose_Bay" : "Canada",
    "America/Grand_Turk" : "Turks and Caicos Islands",
    "America/Grenada" : "Grenada",
    "America/Guadeloupe" : "Guadeloupe",
    "America/Guatemala" : "Guatemala",
    "America/Guayaquil" : "Ecuador",
    "America/Guyana" : "Guyana",
    "America/Halifax" : "Canada",
    "America/Havana" : "Cuba",
    "America/Hermosillo" : "Mexico",
    "America/Indiana/Indianapolis" : "United States",
    "America/Indiana/Knox" : "United States",
    "America/Indiana/Marengo" : "United States",
    "America/Indiana/Petersburg" : "United States",
    "America/Indiana/Tell_City" : "United States",
    "America/Indiana/Vevay" : "United States",
    "America/Indiana/Vincennes" : "United States",
    "America/Indiana/Winamac" : "United States",
    "America/Inuvik" : "Canada",
    "America/Iqaluit" : "Canada",
    "America/Jamaica" : "Jamaica",
    "America/Juneau" : "United States",
    "America/Kentucky/Louisville" : "United States",
    "America/Kentucky/Monticello" : "United States",
    "America/Kralendijk" : "Bonaire",
    "America/La_Paz" : "Bolivia",
    "America/Lima" : "Peru",
    "America/Los_Angeles" : "United States",
    "America/Lower_Princes" : "Sint Maarten",
    "America/Maceio" : "Brazil",
    "America/Managua" : "Nicaragua",
    "America/Manaus" : "Brazil",
    "America/Marigot" : "Saint Martin",
    "America/Martinique" : "Martinique",
    "America/Matamoros" : "Mexico",
    "America/Mazatlan" : "Mexico",
    "America/Menominee" : "United States",
    "America/Merida" : "Mexico",
    "America/Metlakatla" : "United States",
    "America/Mexico_City" : "Mexico",
    "America/Miquelon" : "Saint Pierre and Miquelon",
    "America/Moncton" : "Canada",
    "America/Monterrey" : "Mexico",
    "America/Montevideo" : "Uruguay",
    "America/Montserrat" : "Montserrat",
    "America/Nassau" : "Bahamas",
    "America/New_York" : "United States",
    "America/Nipigon" : "Canada",
    "America/Nome" : "United States",
    "America/Noronha" : "Brazil",
    "America/North_Dakota/Beulah" : "United States",
    "America/North_Dakota/Center" : "United States",
    "America/North_Dakota/New_Salem" : "United States",
    "America/Nuuk" : "Greenland",
    "America/Ojinaga" : "Mexico",
    "America/Panama" : "Panama",
    "America/Pangnirtung" : "Canada",
    "America/Paramaribo" : "Suriname",
    "America/Phoenix" : "United States",
    "America/Port-au-Prince" : "Haiti",
    "America/Port_of_Spain" : "Trinidad and Tobago",
    "America/Porto_Velho" : "Brazil",
    "America/Puerto_Rico" : "Puerto Rico",
    "America/Punta_Arenas" : "Chile",
    "America/Rainy_River" : "Canada",
    "America/Rankin_Inlet" : "Canada",
    "America/Recife" : "Brazil",
    "America/Regina" : "Canada",
    "America/Resolute" : "Canada",
    "America/Rio_Branco" : "Brazil",
    "America/Santa_Isabel" : "Soloman Islands",
    "America/Santarem" : "Brazil",
    "America/Santiago" : "Chile",
    "America/Santo_Domingo" : "Dominican Republic",
    "America/Sao_Paulo" : "Brazil",
    "America/Scoresbysund" : "Greenland",
    "America/Shiprock" : "United States",
    "America/Sitka" : "United States",
    "America/St_Barthelemy" : "Saint Barthelemy",
    "America/St_Johns" : "Canada",
    "America/St_Kitts" : "Saint Kitts and Nevis",
    "America/St_Lucia" : "Saint Lucia",
    "America/St_Thomas" : "Islands",
    "America/St_Vincent" : "Saint Vincent and the Grenadines",
    "America/Swift_Current" : "Canada",
    "America/Tegucigalpa" : "Honduras",
    "America/Thule" : "Greenland",
    "America/Thunder_Bay" : "Canada",
    "America/Tijuana" : "Mexico",
    "America/Toronto" : "Canada",
    "America/Tortola" : "British Virgin Islands",
    "America/Vancouver" : "Canada",
    "America/Whitehorse" : "Canada",
    "America/Winnipeg" : "Canada",
    "America/Yakutat" : "United States",
    "America/Yellowknife" : "Canada",
    "Antarctica/Macquarie" : "Australia",
    "Arctic/Longyearbyen" : "Svalbard and Jan Mayen",
    "Asia/Aden" : "Yemen",
    "Asia/Almaty" : "Kazakhstan",
    "Asia/Amman" : "Jordan",
    "Asia/Anadyr" : "Russia",
    "Asia/Aqtau" : "Kazakhstan",
    "Asia/Aqtobe" : "Kazakhstan",
    "Asia/Ashgabat" : "Turkmenistan",
    "Asia/Atyrau" : "Kazakhstan",
    "Asia/Baghdad" : "Iraq",
    "Asia/Bahrain" : "Bahrain",
    "Asia/Baku" : "Azerbaijan",
    "Asia/Bangkok" : "Thailand",
    "Asia/Barnaul" : "Russia",
    "Asia/Beirut" : "Lebanon",
    "Asia/Bishkek" : "Kyrgyzstan",
    "Asia/Brunei" : "Brunei",
    "Asia/Calcutta" : "India",
    "Asia/Chita" : "Russia",
    "Asia/Choibalsan" : "Mongolia",
    "Asia/Chongqing" : "China",
    "Asia/Colombo" : "Sri Lanka",
    "Asia/Damascus" : "Syria",
    "Asia/Dhaka" : "Bangladesh",
    "Asia/Dili" : "Timor Leste",
    "Asia/Dubai" : "United Arab Emirates",
    "Asia/Dushanbe" : "Tajikistan",
    "Asia/Famagusta" : "Cyprus",
    "Asia/Gaza" : "Palestinian Territory",
    "Asia/Harbin" : "China",
    "Asia/Hebron" : "Palestinian Territory",
    "Asia/Ho_Chi_Minh" : "Vietnam",
    "Asia/Hong_Kong" : "Hong Kong",
    "Asia/Hovd" : "Mongolia",
    "Asia/Irkutsk" : "Russia",
    "Asia/Jakarta" : "Indonesia",
    "Asia/Jayapura" : "Indonesia",
    "Asia/Kabul" : "Afghanistan",
    "Asia/Kamchatka" : "Russia",
    "Asia/Karachi" : "Pakistan",
    "Asia/Kashgar" : "China",
    "Asia/Kathmandu" : "Nepal",
    "Asia/Katmandu" : "Nepal",
    "Asia/Khandyga" : "Russia",
    "Asia/Krasnoyarsk" : "Russia",
    "Asia/Kuala_Lumpur" : "Malaysia",
    "Asia/Kuching" : "Malaysia",
    "Asia/Kuwait" : "Kuwait",
    "Asia/Macau" : "Macao",
    "Asia/Magadan" : "Russia",
    "Asia/Makassar" : "Indonesia",
    "Asia/Manila" : "Philippines",
    "Asia/Muscat" : "Oman",
    "Asia/Nicosia" : "Cyprus",
    "Asia/Novokuznetsk" : "Russia",
    "Asia/Novosibirsk" : "Russia",
    "Asia/Omsk" : "Russia",
    "Asia/Oral" : "Kazakhstan",
    "Asia/Phnom_Penh" : "Cambodia",
    "Asia/Pontianak" : "Indonesia",
    "Asia/Pyongyang" : "North Korea",
    "Asia/Qatar" : "Qatar",
    "Asia/Qostanay" : "Kazakhstan",
    "Asia/Qyzylorda" : "Kazakhstan",
    "Asia/Rangoon" : "Myanmar",
    "Asia/Riyadh" : "Saudi Arabia",
    "Asia/Sakhalin" : "Russia",
    "Asia/Samarkand" : "Uzbekistan",
    "Asia/Seoul" : "South Korea",
    "Asia/Shanghai" : "China",
    "Asia/Singapore" : "Singapore",
    "Asia/Srednekolymsk" : "Russia",
    "Asia/Taipei" : "Taiwan",
    "Asia/Tashkent" : "Uzbekistan",
    "Asia/Tbilisi" : "Georgia",
    "Asia/Tehran" : "Iran",
    "Asia/Thimphu" : "Bhutan",
    "Asia/Tokyo" : "Japan",
    "Asia/Tomsk" : "Russia",
    "Asia/Ulaanbaatar" : "Mongolia",
    "Asia/Urumqi" : "China",
    "Asia/Ust-Nera" : "Russia",
    "Asia/Vientiane" : "Laos",
    "Asia/Vladivostok" : "Russia",
    "Asia/Yakutsk" : "Russia",
    "Asia/Yangon" : "Myanmar",
    "Asia/Yekaterinburg" : "Russia",
    "Asia/Yerevan" : "Armenia",
    "Atlantic/Azores" : "Portugal",
    "Atlantic/Bermuda" : "Bermuda",
    "Atlantic/Canary" : "Spain",
    "Atlantic/Cape_Verde" : "Cabo Verde",
    "Atlantic/Faroe" : "Faroe Islands",
    "Atlantic/Madeira" : "Portugal",
    "Atlantic/Reykjavik" : "Iceland",
    "Atlantic/South_Georgia" : "South Georgia and the South Sandwich Islands",
    "Atlantic/St_Helena" : "Saint Helena",
    "Atlantic/Stanley" : "Falkland Islands",
    "Europe/Amsterdam" : "Netherlands",
    "Europe/Andorra" : "Andorra",
    "Europe/Astrakhan" : "Russia",
    "Europe/Athens" : "Greece",
    "Europe/Belgrade" : "Serbia",
    "Europe/Berlin" : "Germany",
    "Europe/Bratislava" : "Slovakia",
    "Europe/Brussels" : "Belgium",
    "Europe/Bucharest" : "Romania",
    "Europe/Budapest" : "Hungary",
    "Europe/Busingen" : "Germany",
    "Europe/Chisinau" : "Moldova",
    "Europe/Copenhagen" : "Denmark",
    "Europe/Dublin" : "Ireland",
    "Europe/Guernsey" : "United Kingdom",
    "Europe/Helsinki" : "Finland",
    "Europe/Isle_of_Man" : "United Kingdom",
    "Europe/Istanbul" : "Turkey",
    "Europe/Jersey" : "United Kingdom",
    "Europe/Kaliningrad" : "Russia",
    "Europe/Kiev" : "Ukraine",
    "Europe/Kirov" : "Russia",
    "Europe/Lisbon" : "Portugal",
    "Europe/Ljubljana" : "Slovenia",
    "Europe/London" : "United Kingdom",
    "Europe/Luxembourg" : "Luxembourg",
    "Europe/Madrid" : "Spain",
    "Europe/Malta" : "Malta",
    "Europe/Mariehamn" : "Finland",
    "Europe/Minsk" : "Belarus",
    "Europe/Monaco" : "Monaco",
    "Europe/Moscow" : "Russia",
    "Europe/Oslo" : "Norway",
    "Europe/Paris" : "France",
    "Europe/Podgorica" : "Montenegro",
    "Europe/Prague" : "Czechia",
    "Europe/Riga" : "Latvia",
    "Europe/Rome" : "Italy",
    "Europe/Samara" : "Russia",
    "Europe/San_Marino" : "San Marino",
    "Europe/Sarajevo" : "Bosnia and Herzegovina",
    "Europe/Saratov" : "Russia",
    "Europe/Simferopol" : "Russia",
    "Europe/Skopje" : "North Macedonia",
    "Europe/Sofia" : "Bulgaria",
    "Europe/Stockholm" : "Sweden",
    "Europe/Tallinn" : "Estonia",
    "Europe/Tirane" : "Albania",
    "Europe/Ulyanovsk" : "Russia",
    "Europe/Uzhgorod" : "Ukraine",
    "Europe/Vaduz" : "Liechtenstein",
    "Europe/Vatican" : "Vatican City",
    "Europe/Vienna" : "Austria",
    "Europe/Vilnius" : "Lithuania",
    "Europe/Volgograd" : "Russia",
    "Europe/Warsaw" : "Poland",
    "Europe/Zagreb" : "Croatia",
    "Europe/Zaporozhye" : "Ukraine",
    "Europe/Zurich" : "Switzerland",
    "Indian/Antananarivo" : "Madagascar",
    "Indian/Chagos" : "British Indian Ocean Territory",
    "Indian/Christmas" : "Christmas Island",
    "Indian/Cocos" : "Cocos Islands",
    "Indian/Comoro" : "Comoros",
    "Indian/Kerguelen" : "French Southern Territories",
    "Indian/Mahe" : "Seychelles",
    "Indian/Maldives" : "Maldives",
    "Indian/Mauritius" : "Mauritius",
    "Indian/Mayotte" : "Mayotte",
    "Indian/Reunion" : "Reunion",
    "Pacific/Apia" : "Samoa",
    "Pacific/Auckland" : "New Zealand",
    "Pacific/Bougainville" : "Papua New Guinea",
    "Pacific/Chatham" : "New Zealand",
    "Pacific/Chuuk" : "Micronesia",
    "Pacific/Easter" : "Chile",
    "Pacific/Efate" : "Vanuatu",
    "Pacific/Enderbury" : "Kiribati",
    "Pacific/Fakaofo" : "Tokelau",
    "Pacific/Fiji" : "Fiji",
    "Pacific/Funafuti" : "Tuvalu",
    "Pacific/Galapagos" : "Ecuador",
    "Pacific/Gambier" : "French Polynesia",
    "Pacific/Guadalcanal" : "Solomon Islands",
    "Pacific/Guam" : "Guam",
    "Pacific/Honolulu" : "United States",
    "Pacific/Kiritimati" : "Kiribati",
    "Pacific/Kosrae" : "Micronesia",
    "Pacific/Kwajalein" : "Marshall Islands",
    "Pacific/Majuro" : "Marshall Islands",
    "Pacific/Marquesas" : "French Polynesia",
    "Pacific/Midway" : "United States Minor Outlying Islands",
    "Pacific/Nauru" : "Nauru",
    "Pacific/Niue" : "Niue",
    "Pacific/Norfolk" : "Norfolk Island",
    "Pacific/Noumea" : "New Caledonia",
    "Pacific/Pago_Pago" : "American Samoa",
    "Pacific/Palau" : "Palau",
    "Pacific/Pitcairn" : "Pitcairn",
    "Pacific/Pohnpei" : "Micronesia",
    "Pacific/Port_Moresby" : "Papua New Guinea",
    "Pacific/Rarotonga" : "Cook Islands",
    "Pacific/Saipan" : "Northern Mariana Islands",
    "Pacific/Tahiti" : "French Polynesia",
    "Pacific/Tarawa" : "Kiribati",
    "Pacific/Tongatapu" : "Tonga",
    "Pacific/Wake" : "United States Minor Outlying Islands",
    "Pacific/Wallis" : "Wallis and Futuna",
]

let alternativeTimeZoneSearchTerms: [String: [String]] = [
//    "Africa/Abidjan" : ["Ivory Coast, Côte d'Ivoire"],
//    "Africa/Accra" : ["Ghana"],
//    "Africa/Addis_Ababa" : ["Ethiopia"],
//    "Africa/Algiers" : ["Algeria"],
//    "Africa/Asmara" : ["Eritrea"],
//    "Africa/Bamako" : ["Mali"],
//    "Africa/Bangui" : ["Central African Republic"],
//    "Africa/Banjul" : ["Gambia"],
//    "Africa/Bissau" : ["Guinea-Bissau"],
//    "Africa/Blantyre" : ["Malawi"],
//    "Africa/Brazzaville" : ["Congo"],
//    "Africa/Bujumbura" : ["Burundi"],
//    "Africa/Cairo" : ["Egypt"],
//    "Africa/Casablanca" : ["Morocco"],
//    "Africa/Conakry" : ["Guinea"],
//    "Africa/Dakar" : ["Senegal"],
//    "Africa/Dar_es_Salaam" : ["Tanzania"],
//    "Africa/Djibouti" : ["East Africa"],
//    "Africa/Douala" : ["Cameroon"],
//    "Africa/Freetown" : ["Sierra Leone"],
//    "Africa/Gaborone" : ["Botswana"],
//    "Africa/Harare" : ["Zimbabwe"],
//    "Africa/Johannesburg" : ["South Africa"],
//    "Africa/Juba" : ["South Sudan"],
//    "Africa/Kampala" : ["Uganda"],
//    "Africa/Khartoum" : ["Sudan"],
//    "Africa/Kigali" : ["Rwanda"],
//    "Africa/Kinshasa" : ["Democractic Republic of the Congo"],
//    "Africa/Lagos" : ["Nigeria"],
//    "Africa/Libreville" : ["Gabon"],
//    "Africa/Lome" : ["Togo"],
//    "Africa/Luanda" : ["Angola"],
//    "Africa/Lubumbashi" : ["Democractic Republic of the Congo"],
//    "Africa/Lusaka" : ["Zambia"],
//    "Africa/Malabo" : ["Equatorial Guinea"],
//    "Africa/Maputo" : ["Mozambique"],
//    "Africa/Maseru" : ["Lesotho"],
//    "Africa/Mbabane" : ["Swaziland"],
//    "Africa/Mogadishu" : ["Somalia"],
//    "Africa/Monrovia" : ["Liberia"],
//    "Africa/Nairobi" : ["Kenya"],
//    "Africa/Ndjamena" : ["Chad"],
//    "Africa/Niamey" : ["Niger"],
//    "Africa/Nouakchott" : ["Mauritania"],
//    "Africa/Ouagadougou" : ["Brukina Faso"],
//    "Africa/Porto-Novo" : ["Benin"],
//    "Africa/Sao_Tome" : ["Central Africa"],
//    "Africa/Tripoli" : ["Libya"],
//    "Africa/Tunis" : ["Tunisia"],
//    "Africa/Windhoek" : ["Namibia"],
    "America/Adak" : ["Alaska"],
    "America/Anchorage" : ["Alaska"],
//    "America/Araguaina" : ["Brazil"],
//    "America/Asuncion" : ["Paraguay"],
//    "America/Atikokan" : ["Canada"],
//    "America/Bahia" : ["Brazil"],
//    "America/Bahia_Banderas" : ["Mexico"],
//    "America/Belem" : ["Brazil"],
//    "America/Belize" : ["Belize"],
//    "America/Blanc-Sablon" : ["Canada"],
//    "America/Boa_Vista" : ["Brazil"],
//    "America/Bogota" : ["Colombia"],
    "America/Boise" : ["Idaho"],
//    "America/Cambridge_Bay" : ["Canada"],
//    "America/Campo_Grande" : ["Brazil"],
//    "America/Cancun" : ["Mexico"],
//    "America/Caracas" : ["Venezuela"],
//    "America/Cayenne" : ["French Guiana"],
//    "America/Cayman" : ["Cayman Islands"],
    "America/Chicago" : ["Illinois"],
//    "America/Chihuahua" : ["Mexico"],
//    "America/Costa_Rica" : ["Costa Rica"],
//    "America/Creston" : ["Canada"],
//    "America/Cuiaba" : ["Brazil"],
//    "America/Curacao" : ["Curacao"],
//    "America/Danmarkshavn" : ["Greenland"],
//    "America/Dawson" : ["Canada"],
//    "America/Dawson_Creek" : ["Canada"],
    "America/Denver" : ["Colorado"],
    "America/Detroit" : ["Michigan"],
//    "America/Dominica" : ["Dominica"],
//    "America/Edmonton" : ["Canada"],
//    "America/Eirunepe" : ["Brazil"],
//    "America/El_Salvador" : ["El Salvador"],
//    "America/Fort_Nelson" : ["Canada"],
//    "America/Fortaleza" : ["Brazil"],
//    "America/Glace_Bay" : ["Canada"],
//    "America/Godthab" : ["Greenland"],
//    "America/Goose_Bay" : ["Canada"],
//    "America/Grand_Turk" : ["Turks and Caicos Islands"],
//    "America/Grenada" : ["Grenada"],
//    "America/Guadeloupe" : ["Guadeloupe"],
//    "America/Guatemala" : ["Guatemala"],
//    "America/Guayaquil" : ["Ecuador"],
//    "America/Guyana" : ["Guyana"],
//    "America/Halifax" : ["Canada"],
//    "America/Havana" : ["Cuba"],
//    "America/Hermosillo" : ["Mexico"],
//    "America/Indiana/Indianapolis" : ["United States"],
//    "America/Indiana/Knox" : ["United States"],
//    "America/Indiana/Marengo" : ["United States"],
//    "America/Indiana/Petersburg" : ["United States"],
//    "America/Indiana/Tell_City" : ["United States"],
//    "America/Indiana/Vevay" : ["United States"],
//    "America/Indiana/Vincennes" : ["United States"],
//    "America/Indiana/Winamac" : ["United States"],
//    "America/Inuvik" : ["Canada"],
//    "America/Iqaluit" : ["Canada"],
//    "America/Jamaica" : ["Jamaica"],
    "America/Juneau" : ["Alaska"],
//    "America/Kentucky/Louisville" : ["United States"],
//    "America/Kentucky/Monticello" : ["United States"],
//    "America/Kralendijk" : ["Bonaire"],
//    "America/La_Paz" : ["Bolivia"],
//    "America/Lima" : ["Peru"],
    "America/Los_Angeles" : ["California"],
//    "America/Lower_Princes" : ["Sint Maarten"],
//    "America/Maceio" : ["Brazil"],
//    "America/Managua" : ["Nicaragua"],
//    "America/Manaus" : ["Brazil"],
//    "America/Marigot" : ["Saint Martin"],
//    "America/Martinique" : ["Martinique"],
//    "America/Matamoros" : ["Mexico"],
//    "America/Mazatlan" : ["Mexico"],
    "America/Menominee" : ["Michigan"],
//    "America/Merida" : ["Mexico"],
    "America/Metlakatla" : ["Alaska"],
//    "America/Mexico_City" : ["Mexico"],
//    "America/Miquelon" : ["Saint Pierre and Miquelon"],
//    "America/Moncton" : ["Canada"],
//    "America/Monterrey" : ["Mexico"],
//    "America/Montevideo" : ["Uruguay"],
//    "America/Montserrat" : ["Montserrat"],
//    "America/Nassau" : ["Bahamas"],
//    "America/New_York" : ["United States"],
//    "America/Nipigon" : ["Canada"],
    "America/Nome" : ["Alaska"],
//    "America/Noronha" : ["Brazil"],
//    "America/North_Dakota/Beulah" : ["United States"],
//    "America/North_Dakota/Center" : ["United States"],
//    "America/North_Dakota/New_Salem" : ["United States"],
//    "America/Nuuk" : ["Greenland"],
//    "America/Ojinaga" : ["Mexico"],
//    "America/Panama" : ["Panama"],
//    "America/Pangnirtung" : ["Canada"],
//    "America/Paramaribo" : ["Suriname"],
    "America/Phoenix" : ["Arizona"],
//    "America/Port-au-Prince" : ["Haiti"],
//    "America/Port_of_Spain" : ["Trinidad and Tobago"],
//    "America/Porto_Velho" : ["Brazil"],
//    "America/Puerto_Rico" : ["Puerto Rico"],
//    "America/Punta_Arenas" : ["Chile"],
//    "America/Rainy_River" : ["Canada"],
//    "America/Rankin_Inlet" : ["Canada"],
//    "America/Recife" : ["Brazil"],
//    "America/Regina" : ["Canada"],
//    "America/Resolute" : ["Canada"],
//    "America/Rio_Branco" : ["Brazil"],
//    "America/Santa_Isabel" : ["Soloman Islands"],
//    "America/Santarem" : ["Brazil"],
//    "America/Santiago" : ["Chile"],
//    "America/Santo_Domingo" : ["Dominican Republic"],
//    "America/Sao_Paulo" : ["Brazil"],
//    "America/Scoresbysund" : ["Greenland"],
    "America/Shiprock" : ["New Mexico"],
    "America/Sitka" : ["Alaska"],
//    "America/St_Barthelemy" : ["Saint Barthelemy"],
//    "America/St_Johns" : ["Canada"],
//    "America/St_Kitts" : ["Saint Kitts and Nevis"],
//    "America/St_Lucia" : ["Saint Lucia"],
//    "America/St_Thomas" : ["Islands"],
//    "America/St_Vincent" : ["Saint Vincent and the Grenadines"],
//    "America/Swift_Current" : ["Canada"],
//    "America/Tegucigalpa" : ["Honduras"],
//    "America/Thule" : ["Greenland"],
//    "America/Thunder_Bay" : ["Canada"],
//    "America/Tijuana" : ["Mexico"],
//    "America/Toronto" : ["Canada"],
//    "America/Tortola" : ["British Virgin Islands"],
//    "America/Vancouver" : ["Canada"],
//    "America/Whitehorse" : ["Canada"],
//    "America/Winnipeg" : ["Canada"],
    "America/Yakutat" : ["Alaska"],
//    "America/Yellowknife" : ["Canada"],
//    "Antarctica/Macquarie" : ["Australia"],
//    "Arctic/Longyearbyen" : ["Svalbard and Jan Mayen"],
//    "Asia/Aden" : ["Yemen"],
//    "Asia/Almaty" : ["Kazakhstan"],
//    "Asia/Amman" : ["Jordan"],
//    "Asia/Anadyr" : ["Russia"],
//    "Asia/Aqtau" : ["Kazakhstan"],
//    "Asia/Aqtobe" : ["Kazakhstan"],
//    "Asia/Ashgabat" : ["Turkmenistan"],
//    "Asia/Atyrau" : ["Kazakhstan"],
//    "Asia/Baghdad" : ["Iraq"],
//    "Asia/Bahrain" : ["Bahrain"],
//    "Asia/Baku" : ["Azerbaijan"],
//    "Asia/Bangkok" : ["Thailand"],
//    "Asia/Barnaul" : ["Russia"],
//    "Asia/Beirut" : ["Lebanon"],
//    "Asia/Bishkek" : ["Kyrgyzstan"],
//    "Asia/Brunei" : ["Brunei"],
//    "Asia/Calcutta" : ["India"],
//    "Asia/Chita" : ["Russia"],
//    "Asia/Choibalsan" : ["Mongolia"],
//    "Asia/Chongqing" : ["China"],
//    "Asia/Colombo" : ["Sri Lanka"],
//    "Asia/Damascus" : ["Syria"],
//    "Asia/Dhaka" : ["Bangladesh"],
//    "Asia/Dili" : ["Timor Leste"],
//    "Asia/Dubai" : ["United Arab Emirates"],
//    "Asia/Dushanbe" : ["Tajikistan"],
//    "Asia/Famagusta" : ["Cyprus"],
//    "Asia/Gaza" : ["Palestinian Territory"],
//    "Asia/Harbin" : ["China"],
//    "Asia/Hebron" : ["Palestinian Territory"],
//    "Asia/Ho_Chi_Minh" : ["Vietnam"],
//    "Asia/Hong_Kong" : ["Hong Kong"],
//    "Asia/Hovd" : ["Mongolia"],
//    "Asia/Irkutsk" : ["Russia"],
//    "Asia/Jakarta" : ["Indonesia"],
//    "Asia/Jayapura" : ["Indonesia"],
//    "Asia/Kabul" : ["Afghanistan"],
//    "Asia/Kamchatka" : ["Russia"],
//    "Asia/Karachi" : ["Pakistan"],
//    "Asia/Kashgar" : ["China"],
//    "Asia/Kathmandu" : ["Nepal"],
//    "Asia/Katmandu" : ["Nepal"],
//    "Asia/Khandyga" : ["Russia"],
//    "Asia/Krasnoyarsk" : ["Russia"],
//    "Asia/Kuala_Lumpur" : ["Malaysia"],
//    "Asia/Kuching" : ["Malaysia"],
//    "Asia/Kuwait" : ["Kuwait"],
//    "Asia/Macau" : ["Macao"],
//    "Asia/Magadan" : ["Russia"],
//    "Asia/Makassar" : ["Indonesia"],
//    "Asia/Manila" : ["Philippines"],
//    "Asia/Muscat" : ["Oman"],
//    "Asia/Nicosia" : ["Cyprus"],
//    "Asia/Novokuznetsk" : ["Russia"],
//    "Asia/Novosibirsk" : ["Russia"],
//    "Asia/Omsk" : ["Russia"],
//    "Asia/Oral" : ["Kazakhstan"],
//    "Asia/Phnom_Penh" : ["Cambodia"],
//    "Asia/Pontianak" : ["Indonesia"],
//    "Asia/Pyongyang" : ["North Korea"],
//    "Asia/Qatar" : ["Qatar"],
//    "Asia/Qostanay" : ["Kazakhstan"],
//    "Asia/Qyzylorda" : ["Kazakhstan"],
//    "Asia/Rangoon" : ["Myanmar"],
//    "Asia/Riyadh" : ["Saudi Arabia"],
//    "Asia/Sakhalin" : ["Russia"],
//    "Asia/Samarkand" : ["Uzbekistan"],
//    "Asia/Seoul" : ["South Korea"],
//    "Asia/Shanghai" : ["China"],
//    "Asia/Singapore" : ["Singapore"],
//    "Asia/Srednekolymsk" : ["Russia"],
//    "Asia/Taipei" : ["Taiwan"],
//    "Asia/Tashkent" : ["Uzbekistan"],
//    "Asia/Tbilisi" : ["Georgia"],
//    "Asia/Tehran" : ["Iran"],
//    "Asia/Thimphu" : ["Bhutan"],
//    "Asia/Tokyo" : ["Japan"],
//    "Asia/Tomsk" : ["Russia"],
//    "Asia/Ulaanbaatar" : ["Mongolia"],
//    "Asia/Urumqi" : ["China"],
//    "Asia/Ust-Nera" : ["Russia"],
//    "Asia/Vientiane" : ["Laos"],
//    "Asia/Vladivostok" : ["Russia"],
//    "Asia/Yakutsk" : ["Russia"],
//    "Asia/Yangon" : ["Myanmar"],
//    "Asia/Yekaterinburg" : ["Russia"],
//    "Asia/Yerevan" : ["Armenia"],
//    "Atlantic/Azores" : ["Portugal"],
//    "Atlantic/Bermuda" : ["Bermuda"],
//    "Atlantic/Canary" : ["Spain"],
//    "Atlantic/Cape_Verde" : ["Cabo Verde"],
//    "Atlantic/Faroe" : ["Faroe Islands"],
//    "Atlantic/Madeira" : ["Portugal"],
//    "Atlantic/Reykjavik" : ["Iceland"],
//    "Atlantic/South_Georgia" : ["South Georgia and the South Sandwich Islands"],
//    "Atlantic/St_Helena" : ["Saint Helena"],
//    "Atlantic/Stanley" : ["Falkland Islands"],
    "Australia/Adelaide": ["South Australia"],
    "Australia/Brisbane": ["Queensland", "QLD", "Ginger"],
    "Australia/Broken_Hill": ["New South Wales", "NSW"],
    "Australia/Currie": ["Tasmania"],
    "Australia/Darwin": ["Northern Territory"],
    "Australia/Eucla": ["Western Australia"],
    "Australia/Hobart": ["Tasmania"],
    "Australia/Lindeman": ["Queensland", "QLD"],
    "Australia/Lord_Howe": [],
    "Australia/Melbourne": ["Victoria"],
    "Australia/Perth": ["Western Australia"],
    "Australia/Sydney": ["New South Wales", "NSW"],
//    "Europe/Amsterdam" : ["Netherlands"],
//    "Europe/Andorra" : ["Andorra"],
//    "Europe/Astrakhan" : ["Russia"],
//    "Europe/Athens" : ["Greece"],
//    "Europe/Belgrade" : ["Serbia"],
//    "Europe/Berlin" : ["Germany"],
//    "Europe/Bratislava" : ["Slovakia"],
//    "Europe/Brussels" : ["Belgium"],
//    "Europe/Bucharest" : ["Romania"],
//    "Europe/Budapest" : ["Hungary"],
//    "Europe/Busingen" : ["Germany"],
//    "Europe/Chisinau" : ["Moldova"],
//    "Europe/Copenhagen" : ["Denmark"],
//    "Europe/Dublin" : ["Ireland"],
    "Europe/Guernsey" : ["Channel Islands"],
//    "Europe/Helsinki" : ["Finland"],
//    "Europe/Isle_of_Man" : ["United Kingdom"],
//    "Europe/Istanbul" : ["Turkey"],
    "Europe/Jersey" : ["Channel Islands"],
//    "Europe/Kaliningrad" : ["Russia"],
//    "Europe/Kiev" : ["Ukraine"],
//    "Europe/Kirov" : ["Russia"],
//    "Europe/Lisbon" : ["Portugal"],
//    "Europe/Ljubljana" : ["Slovenia"],
    "Europe/London" : ["England", "Scotland", "Wales", "Great Britain", "Brits"],
//    "Europe/Luxembourg" : ["Luxembourg"],
//    "Europe/Madrid" : ["Spain"],
//    "Europe/Malta" : ["Malta"],
//    "Europe/Mariehamn" : ["Finland"],
//    "Europe/Minsk" : ["Belarus"],
//    "Europe/Monaco" : ["Monaco"],
//    "Europe/Moscow" : ["Russia"],
//    "Europe/Oslo" : ["Norway"],
//    "Europe/Paris" : ["France"],
//    "Europe/Podgorica" : ["Montenegro"],
//    "Europe/Prague" : ["Czechia"],
//    "Europe/Riga" : ["Latvia"],
//    "Europe/Rome" : [],
//    "Europe/Samara" : ["Russia"],
//    "Europe/San_Marino" : ["San Marino"],
//    "Europe/Sarajevo" : ["Bosnia and Herzegovina"],
//    "Europe/Saratov" : ["Russia"],
//    "Europe/Simferopol" : ["Russia"],
//    "Europe/Skopje" : ["North Macedonia"],
//    "Europe/Sofia" : ["Bulgaria"],
//    "Europe/Stockholm" : ["Sweden"],
//    "Europe/Tallinn" : ["Estonia"],
//    "Europe/Tirane" : ["Albania"],
//    "Europe/Ulyanovsk" : ["Russia"],
//    "Europe/Uzhgorod" : ["Ukraine"],
//    "Europe/Vaduz" : ["Liechtenstein"],
//    "Europe/Vatican" : ["Vatican City"],
//    "Europe/Vienna" : ["Austria"],
//    "Europe/Vilnius" : ["Lithuania"],
//    "Europe/Volgograd" : ["Russia"],
//    "Europe/Warsaw" : ["Poland"],
//    "Europe/Zagreb" : ["Croatia"],
//    "Europe/Zaporozhye" : ["Ukraine"],
//    "Europe/Zurich" : ["Switzerland"],
//    "Indian/Antananarivo" : ["Madagascar"],
//    "Indian/Chagos" : ["British Indian Ocean Territory"],
//    "Indian/Christmas" : ["Christmas Island"],
//    "Indian/Cocos" : ["Cocos Islands"],
//    "Indian/Comoro" : ["Comoros"],
//    "Indian/Kerguelen" : ["French Southern Territories"],
//    "Indian/Mahe" : ["Seychelles"],
//    "Indian/Maldives" : ["Maldives"],
//    "Indian/Mauritius" : ["Mauritius"],
//    "Indian/Mayotte" : ["Mayotte"],
//    "Indian/Reunion" : ["Reunion"],
//    "Pacific/Apia" : ["Samoa"],
//    "Pacific/Auckland" : ["New Zealand"],
//    "Pacific/Bougainville" : ["Papua New Guinea"],
//    "Pacific/Chatham" : ["New Zealand"],
//    "Pacific/Chuuk" : ["Micronesia"],
//    "Pacific/Easter" : ["Chile"],
//    "Pacific/Efate" : ["Vanuatu"],
//    "Pacific/Enderbury" : ["Kiribati"],
//    "Pacific/Fakaofo" : ["Tokelau"],
//    "Pacific/Fiji" : ["Fiji"],
//    "Pacific/Funafuti" : ["Tuvalu"],
//    "Pacific/Galapagos" : ["Ecuador"],
//    "Pacific/Gambier" : ["French Polynesia"],
//    "Pacific/Guadalcanal" : ["Solomon Islands"],
//    "Pacific/Guam" : ["Guam"],
//    "Pacific/Honolulu" : ["United States"],
//    "Pacific/Kiritimati" : ["Kiribati"],
//    "Pacific/Kosrae" : ["Micronesia"],
//    "Pacific/Kwajalein" : ["Marshall Islands"],
//    "Pacific/Majuro" : ["Marshall Islands"],
//    "Pacific/Marquesas" : ["French Polynesia"],
//    "Pacific/Midway" : ["United States Minor Outlying Islands"],
//    "Pacific/Nauru" : ["Nauru"],
//    "Pacific/Niue" : ["Niue"],
//    "Pacific/Norfolk" : ["Norfolk Island"],
//    "Pacific/Noumea" : ["New Caledonia"],
//    "Pacific/Pago_Pago" : ["American Samoa"],
//    "Pacific/Palau" : ["Palau"],
//    "Pacific/Pitcairn" : ["Pitcairn"],
//    "Pacific/Pohnpei" : ["Micronesia"],
//    "Pacific/Port_Moresby" : ["Papua New Guinea"],
//    "Pacific/Rarotonga" : ["Cook Islands"],
//    "Pacific/Saipan" : ["Northern Mariana Islands"],
//    "Pacific/Tahiti" : ["French Polynesia"],
//    "Pacific/Tarawa" : ["Kiribati"],
//    "Pacific/Tongatapu" : ["Tonga"],
//    "Pacific/Wake" : ["United States Minor Outlying Islands"],
//    "Pacific/Wallis" : ["Wallis and Futuna"],
    "IST": ["India", "Indian Standard Time"],
]
